import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ShieldCheck, Zap, BarChart3, ChevronRight } from 'lucide-react';

const Home = () => {
  return (
    <div className="min-h-screen pt-20 overflow-hidden">
      {/* Hero Section */}
      <section className="relative max-w-7xl mx-auto px-6 pt-20 pb-32 flex flex-col items-center text-center">
        {/* Decorative background blur */}
        <div className="absolute top-0 -z-10 w-72 h-72 bg-blue-400/20 rounded-full blur-[120px]" />
        
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <span className="neo-inset px-4 py-2 rounded-full text-[10px] font-black text-blue-600 uppercase tracking-[0.3em] mb-6 inline-block">
            Powered by Team DHURANDAR
          </span>
          <h1 className="text-6xl md:text-8xl font-black tracking-tighter text-slate-800 leading-[0.9]">
            Precision Medicine.<br />
            <span className="text-blue-600">Zero Guesswork.</span>
          </h1>
          <p className="mt-8 text-lg text-slate-500 max-w-2xl mx-auto leading-relaxed">
            PharmaGuard analyzes patient genomic variants in real-time to predict drug responses and prevent adverse reactions using clinical CPIC guidelines.
          </p>

          <div className="mt-12 flex flex-col sm:flex-row items-center justify-center gap-6">
            <Link to="/dashboard">
              <motion.button 
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="px-10 py-5 rounded-2xl bg-blue-600 text-white font-black shadow-lg shadow-blue-500/40 flex items-center gap-2 group"
              >
                Launch Dashboard <ChevronRight size={18} className="group-hover:translate-x-1 transition-transform" />
              </motion.button>
            </Link>
            <Link to="/about">
              <button className="px-10 py-5 rounded-2xl neo-flat font-black text-slate-600 hover:text-blue-600 transition-colors">
                View Documentation
              </button>
            </Link>
          </div>
        </motion.div>

        {/* Feature Grid */}
        <div className="mt-32 grid grid-cols-1 md:grid-cols-3 gap-8 w-full">
          {[
            { 
              icon: <ShieldCheck className="text-blue-600" />, 
              title: "Clinical Safety", 
              desc: "Cross-referenced with CPIC and PharmGKB clinical guidelines." 
            },
            { 
              icon: <Zap className="text-blue-600" />, 
              title: "Instant Parsing", 
              desc: "Upload complex VCF files and get results in under 5 seconds." 
            },
            { 
              icon: <BarChart3 className="text-blue-600" />, 
              title: "AI Explanations", 
              desc: "Deep pathophysiological insights generated by LLMs." 
            }
          ].map((feature, i) => (
            <motion.div 
              key={i}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 + (i * 0.1) }}
              className="glass-panel p-8 rounded-[40px] text-left hover:bg-white/40 transition-all border border-white/50"
            >
              <div className="w-12 h-12 rounded-2xl neo-flat flex items-center justify-center mb-6">
                {feature.icon}
              </div>
              <h4 className="font-black text-slate-800 uppercase tracking-tight">{feature.title}</h4>
              <p className="text-sm text-slate-500 mt-2 leading-relaxed">{feature.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Stats Section / Social Proof */}
      <section className="bg-white/10 backdrop-blur-sm border-y border-white/20 py-12">
        <div className="max-w-7xl mx-auto px-6 flex flex-wrap justify-around gap-8">
          {[
            { label: "Processing Speed", val: "< 2s" },
            { label: "Accuracy Rate", val: "99.9%" },
            { label: "Variants Tracked", val: "50k+" },
            { label: "Clinical Models", val: "CPIC v3" },
          ].map((stat, i) => (
            <div key={i} className="text-center">
              <p className="text-[10px] font-black text-blue-500 uppercase tracking-widest">{stat.label}</p>
              <p className="text-3xl font-black text-slate-800">{stat.val}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default Home;